### PR TITLE
Eslint fix

### PR DESCRIPTION
**Pull request by kennetvu**
- Added lint as script
- Added .idea folder to gitignore
- Added .eslintrc to stories

### CODE REVIEW

**Comment by kennetvu** [comment]
Dont merge yet, seems like I have broke the storybook

**Comment by alexanbj** [comment]
I changed the storybook config so it dynamically requires the stories.
Should be easy enough to change the reg exp to account for jsx files.

**Comment by kennetvu** [comment]
I tested storybook on `master` and it seems like you broke master too.

**Comment by kennetvu** [comment]
I figured it out, .babelrc is breaking storybook on `master`

**Comment by kennetvu** [comment]
I fixed it... Its in PR #2

**Pull request merged**
